### ISSUE TITLE
Error when installing the module on a project

### ISSUE THREAD

**Issue by wernerkrauss** [nswdpc/silverstripe-elemental-feature-video#2]
Hi, I just installed your module on a project and encountered an error when running dev/build:

> [Emergency] Uncaught InvalidArgumentException: NSWDPC\Elemental\Models\FeaturedVideo\ElementVideo references nonexistent gorriecoe\Embed\Extensions\Embeddable in 'extensions'

Is this module needed? If yes, it'd be great if it was a requirement of the module itself.

Thanks for sharing your elemental blocks!

**Comment by tardinha** [comment]
Sorry about that! I bashed this out in a hurry, and didn't notice. Thanks for the pick up!

This has been fixed, and I've bumped the version.
